export const ENEMY_SPRITE_KEY = 'enemy-squirrel';
export const ENEMY_ANIMATION_PREFIX = 'enemy';
/** Grey squirrels share the brown sheet's layout; the texture is recoloured at boot. */
export const GREY_ENEMY_SPRITE_KEY = 'enemy-squirrel-grey';
export const GREY_ENEMY_ANIMATION_PREFIX = 'enemy-grey';
/** Deer sheets are generated by scripts/build_deer.py with the squirrel sheet's layout. */
export const DOE_SPRITE_KEY = 'enemy-doe';
export const DOE_ANIMATION_PREFIX = 'enemy-doe';
export const FAWN_SPRITE_KEY = 'enemy-fawn';
export const FAWN_ANIMATION_PREFIX = 'enemy-fawn';
export const BUCK_SPRITE_KEY = 'enemy-buck';
export const BUCK_ANIMATION_PREFIX = 'enemy-buck';
export const ARMADILLO_SPRITE_KEY = 'enemy-armadillo';
export const ARMADILLO_ROLL_KEY = 'enemy-armadillo-roll';
export const ARMADILLO_ANIMATION_PREFIX = 'enemy-armadillo';
export const ENEMY_FRAME_SIZE = 64;
export const ENEMY_FRAMES_PER_ROW = 4;

export const ENEMY_ANIMATION_ROWS = [
  ['walk-down', 0, 8],
  ['walk-down-right', 1, 8],
  ['walk-right', 2, 8],
  ['walk-up-right', 3, 8],
  ['walk-up', 4, 8],
  ['walk-up-left', 5, 8],
  ['walk-left', 6, 8],
  ['walk-down-left', 7, 8]
] as const;

const WALK_NAME_BY_DIRECTION: Record<string, string> = {
  '0,1': 'walk-down',
  '1,1': 'walk-down-right',
  '1,0': 'walk-right',
  '1,-1': 'walk-up-right',
  '0,-1': 'walk-up',
  '-1,-1': 'walk-up-left',
  '-1,0': 'walk-left',
  '-1,1': 'walk-down-left'
};

function withPrefix(prefix: string): Record<string, string> {
  return Object.fromEntries(Object.entries(WALK_NAME_BY_DIRECTION).map(([k, v]) => [k, `${prefix}-${v}`]));
}

export const ENEMY_WALK_ANIMATION_BY_DIRECTION = withPrefix(ENEMY_ANIMATION_PREFIX);
export const GREY_ENEMY_WALK_ANIMATION_BY_DIRECTION = withPrefix(GREY_ENEMY_ANIMATION_PREFIX);
export const DOE_WALK_ANIMATION_BY_DIRECTION = withPrefix(DOE_ANIMATION_PREFIX);
export const FAWN_WALK_ANIMATION_BY_DIRECTION = withPrefix(FAWN_ANIMATION_PREFIX);
export const BUCK_WALK_ANIMATION_BY_DIRECTION = withPrefix(BUCK_ANIMATION_PREFIX);
export const ARMADILLO_WALK_ANIMATION_BY_DIRECTION = withPrefix(ARMADILLO_ANIMATION_PREFIX);
export const ARMADILLO_ROLL_ANIMATION = 'armadillo-roll';
