import Phaser from 'phaser';
// Pixel-art buzzard, generated by scripts/build_buzzard.py (same 6 x 2 layout of 192px cells).
import url from '../../assets/sprites/buzzard-pixel-sheet.png';
import kingUrl from '../../assets/sprites/king-frankie-sheet.png';
import portrait from '../../assets/sprites/buzzard-pixel-portrait.png';
import feather from '../../assets/sprites/frankie-feather.png';

import { FRANKIE_DIVE_KEY, FRANKIE_FLAP_KEY, FRANKIE_SPRITE_KEY, KING_FRANKIE_DIVE_KEY, KING_FRANKIE_FLAP_KEY, KING_FRANKIE_SPRITE_KEY } from './frankieKeys';

export { FRANKIE_DIVE_KEY, FRANKIE_FLAP_KEY, FRANKIE_SPRITE_KEY, KING_FRANKIE_DIVE_KEY, KING_FRANKIE_FLAP_KEY, KING_FRANKIE_SPRITE_KEY };
export const FRANKIE_SPRITE_URL = url;
export const KING_FRANKIE_SPRITE_URL = kingUrl;
export const FRANKIE_PORTRAIT_URL = portrait;
export const FRANKIE_FEATHER_URL = feather;
export const FRANKIE_PORTRAIT_KEY = 'companion-frankie-portrait';
export const FRANKIE_FRAME_SIZE = 192;
export const FRANKIE_FRAMES_PER_ROW = 6;

export function createFrankieAnimations(scene: Phaser.Scene): void {
  for (const [sheet, flap, dive] of [[FRANKIE_SPRITE_KEY, FRANKIE_FLAP_KEY, FRANKIE_DIVE_KEY],
    [KING_FRANKIE_SPRITE_KEY, KING_FRANKIE_FLAP_KEY, KING_FRANKIE_DIVE_KEY]]) {
    if (!scene.anims.exists(flap)) {
      scene.anims.create({ key: flap, frames: scene.anims.generateFrameNumbers(sheet, { start: 0, end: 5 }), frameRate: 10, repeat: -1 });
    }
    if (!scene.anims.exists(dive)) {
      scene.anims.create({ key: dive, frames: scene.anims.generateFrameNumbers(sheet, { start: 6, end: 9 }), frameRate: 12, repeat: -1 });
    }
  }
}
