import Phaser from 'phaser';

/**
 * Ron's sheet is generated by `scripts/build_ron_bard.py`: 8 columns by 8 rows of 192px cells,
 * laid out exactly like the Code Wizard sheet so the same walk rig and animation rows apply.
 * Row 0 is his idle, rows 1-7 are eight-frame stride cycles.
 */
export const RON_SPRITE_KEY = 'player-ron';
export const RON_ANIMATION_PREFIX = 'ron';
export const RON_FRAME_SIZE = 192;
export const RON_FRAMES_PER_ROW = 8;

/** [animation name, sheet row, frame rate] — matches PLAYER_ANIMATION_ROWS. */
export const RON_ANIMATION_ROWS = [
  ['idle-down', 0, 2],
  ['walk-down', 1, 12],
  ['walk-down-right', 2, 12],
  ['walk-right', 3, 12],
  ['walk-up-left', 4, 12],
  ['walk-up', 5, 12],
  ['walk-left', 6, 12],
  ['walk-down-left', 7, 12]
] as const;

export function createRonAnimations(scene: Phaser.Scene): void {
  for (const [name, row, frameRate] of RON_ANIMATION_ROWS) {
    const key = `${RON_ANIMATION_PREFIX}-${name}`;
    if (scene.anims.exists(key)) continue;
    const start = row * RON_FRAMES_PER_ROW;
    scene.anims.create({
      key,
      frames: scene.anims.generateFrameNumbers(RON_SPRITE_KEY, { start, end: start + RON_FRAMES_PER_ROW - 1 }),
      frameRate,
      repeat: -1
    });
  }
}
