import type Phaser from 'phaser';
export { default as stagSheetUrl } from '../../assets/sprites/stag-boss-spritesheet.png';

/**
 * Generated by scripts/build_stag.py: 128px cells. Rows 0-1 face right, rows 2-3 face left.
 * Each half: walk (4), then windup, charge A, charge B, rest. Wonky's antlers are lopsided
 * (three points left, five right), so left-facing frames are drawn, not flipped.
 */
export const STAG_TEXTURE = 'stag-boss';
export const STAG_FRAME_SIZE = 128;
export const STAG_FRAMES = { walk: [0, 1, 2, 3], windup: 4, charge: [5, 6], rest: 7 } as const;
/** Add to any frame above for the left-facing drawing. */
export const STAG_LEFT_OFFSET = 8;

export function createStagAnimations(scene: Phaser.Scene): void {
  for (const [suffix, offset] of [['', 0], ['-left', STAG_LEFT_OFFSET]] as const) {
    if (!scene.anims.exists(`stag-walk${suffix}`)) {
      scene.anims.create({ key: `stag-walk${suffix}`, frames: STAG_FRAMES.walk.map(frame => ({ key: STAG_TEXTURE, frame: frame + offset })), frameRate: 8, repeat: -1 });
    }
    if (!scene.anims.exists(`stag-charge${suffix}`)) {
      scene.anims.create({ key: `stag-charge${suffix}`, frames: STAG_FRAMES.charge.map(frame => ({ key: STAG_TEXTURE, frame: frame + offset })), frameRate: 12, repeat: -1 });
    }
  }
}
