import type Phaser from 'phaser';
export { default as stagSheetUrl } from '../../assets/sprites/stag-boss-spritesheet.png';

/** Generated by scripts/build_stag.py: 128px cells, row 0 walk (4), row 1 windup, charge A, charge B, rest. */
export const STAG_TEXTURE = 'stag-boss';
export const STAG_FRAME_SIZE = 128;
export const STAG_FRAMES = { walk: [0, 1, 2, 3], windup: 4, charge: [5, 6], rest: 7 } as const;

export function createStagAnimations(scene: Phaser.Scene): void {
  if (!scene.anims.exists('stag-walk')) {
    scene.anims.create({ key: 'stag-walk', frames: STAG_FRAMES.walk.map(frame => ({ key: STAG_TEXTURE, frame })), frameRate: 8, repeat: -1 });
  }
  if (!scene.anims.exists('stag-charge')) {
    scene.anims.create({ key: 'stag-charge', frames: STAG_FRAMES.charge.map(frame => ({ key: STAG_TEXTURE, frame })), frameRate: 12, repeat: -1 });
  }
}
